# Build Bleach-Save-Comparator

name: Build Bleach-Save-Comparator 

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'  
      - 'README.md'
      
jobs:
  build-Windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Compile GUI
      run: |
        pyinstaller --onefile --noconsole --icon=imgs/icon.ico Bleach-Save-Comparator.py

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create v1.1.0 dist/Bleach-Save-Comparator.exe --title "Bleach-Save-Comparator v1.1" 
